//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class companies
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long DirectorId { get; set; }
        public long DialogId { get; set; }
    
        public virtual dialogs dialogs { get; set; }
        public virtual users users { get; set; }
    }
}
