//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_mails
    {
        public long Id { get; set; }
        public long user_id { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public Nullable<long> attachment_id { get; set; }
        public string name { get; set; }
        public Nullable<int> group_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
