//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gbua_adminclubEntities : DbContext
    {
        public gbua_adminclubEntities()
            : base("name=gbua_adminclubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public virtual DbSet<client_status> client_status { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<companies> companies { get; set; }
        public virtual DbSet<delivery_mails> delivery_mails { get; set; }
        public virtual DbSet<dialogs> dialogs { get; set; }
        public virtual DbSet<invites> invites { get; set; }
        public virtual DbSet<mails> mails { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<notes> notes { get; set; }
        public virtual DbSet<permissions> permissions { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sent_delivery_mails> sent_delivery_mails { get; set; }
        public virtual DbSet<sites> sites { get; set; }
        public virtual DbSet<sitesfotosetting> sitesfotosetting { get; set; }
        public virtual DbSet<timetables> timetables { get; set; }
        public virtual DbSet<user_clients> user_clients { get; set; }
        public virtual DbSet<user_data> user_data { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
