//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissions
    {
        public long Id { get; set; }
        public long RoleId { get; set; }
        public string Name { get; set; }
        public bool IsAllowed { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
