//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitesfotosetting
    {
        public long Id { get; set; }
        public string name { get; set; }
        public int width { get; set; }
        public int heigth { get; set; }
        public int size { get; set; }
        public int Profile_img_width { get; set; }
        public int Profile_img_heigth { get; set; }
        public int VideoWidth { get; set; }
        public int VideoHeigth { get; set; }
        public string VideoFormat { get; set; }
        public int videoSize { get; set; }
        public bool isFixedResolution { get; set; }
        public int HorizontalWidth { get; set; }
        public int HorizontalHeigth { get; set; }
    }
}
