//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_clients
    {
        public long Id { get; set; }
        public long user_id { get; set; }
        public long site_id { get; set; }
        public long client_id { get; set; }
        public Nullable<long> Sent_delivery_mail { get; set; }
    
        public virtual sites sites { get; set; }
        public virtual users users { get; set; }
    }
}
